sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: dwHfeKxCfUmJSRNaV8u8ZSqNp0yCnP8BodTOqkTOOI/2cJKji62TbkMs3GqXammYT+icwpiefMUOnGYHXg0teFn+RObROkEu4ilNH02HxFIvEET03epOgzGZLuLog0aCgHlNlD+jp6wIadhxa84uCi0E6t2GLahmIXkKpg0TTS7sqRk5kRXiAJaRpjWCNQTNZYm1yWZVCuGxMrq8sI1cNboQMVO8Ff2C2ry6lUnam+HVm1cp0y4Z7RNUkHCMRpZJxTr1tGAZVw7CUWCT0+u07S94P0ozjpb4MreKA8Nn1B0OcwMFRi+hsPJZ2X3Wn2dwlxvwDKh+Kf5z2jWy46kguj7P3frJ+OLsBQQB/RDtm0H3xxJmhqOGk/FwWRplJNTy50KmCM0DCk8RlsDnOAk2O9Ye6U64YrUJiyhL69ch1ZEks+rUzE6zTcNqR0yUM2MwyBIrIbWA1FoC+xbx5Dzz/M0S+JcVmYqZoV28deX8lCF6jGHYldVwuR620cUMmjXHUR1N49Fl7PW1B4Tt6A49adCDhvoiDEWiHGEH0+gNfZSUyNd8Ns1Hmg75Tmo+7XKnm1gF9cBGXw56zMA8cKABn1JSv/+p6rroz26eX5x3lLplJyQ2Zv1nWibUbype0fOxZIJLzOd74plaWRs4/48Pge8I84DUOUvftsLHKGL1yF4=
  - secure: vqCDJsbLPlPchWVw8ZiBH99if9DMmH/8FRaLZoWplJ1rz1d7aODfj0UgzxlMQzyu7EDUiK4YtZBcukyEhnr9a/UaP1l2dXbNqT4Tsfu4m9TgTyWUixoaG4XR6FYGnK8IRMx/zjAPDFMUI6+4ZEbjO1ZTP6bKovSSxLZwOyATO+T9IZLqFtNAPsopEyS0gZwzobrhBINauD14wXJ76jNCEgimFaZ4TYGhI8PZhiJ6QlRxP6AF2QxFQzHBDSBJrT44/uchbHHPv/kg0a9ZzaQFwwK3SruiHNCZzMtTpvBiyydLeRTQbWhEeHtF+X2ovVmelEae3J1rWGCgGdGklNo/bKKNrWtK4GMv89IRPyebhvpUdzU5iG2Vs+vO/Hi7OmkQ9jZwnm9aXn0ZLPe6IaC+ApjwHIjXx9LTKuhqKKL34m8+/Sf7k4ZFBv8adSoJszJcw5pKPRVp4KzmxhMhfEdV5QKKFsmwftZPakyx/ZdT2NvJ8Eq4kwtW0Btw1Jzp1VHI6OUPR5ix39ThGVWU3mVqOVUbXMVO5/zmDuyTubqt7TZOhoQVjRkaPkqnLfcjYHFS+hGmsth2wgz1ntImkyFT7PnM2RhVHChigDyU/HyCIrmI+Xqz5h7bX7QB/2tI1u67Q1xMWeoZJbVCoAmelQzcaKm5Ym8CCkgihSMVVFaJmfY=
  - secure: gTDukHQDTgbza/xfy6YWWwX4AygdG7vAJ3idI0uCAVhHQSkwJBB8UROj6vnVxpSfT+PDBmhscG7qvq43pYRjAE6/81ffEFt9VfA6pFpHSSaqwQVR8EVCcAy1af1Auble5oe4bamsLoSfEd4mZm67PXs6FAUalVRTcEWmMtmWXj4xC4XJGxzVuOb7ckWoPIC27JO/UMIW/Tw1LghjBvZ7Y9zx/EpELoU7a+beWZXThR7mj1jAWYWiEh3hTXoZGQ41+hA+/qJXAjwiyT0APvP1aPBsWk7RDZfuj7oyt5lb/99yb/JyRpph1Caj2MptFnMOIjFXUOEdYltwePp0vdfO4TXiu/bxICqrk1E2PnAx+B0XP8TGffXPLc1FL+fatDXi3in1xxjfYgfWowCnC6gpbntNOorgiFYo12GYZ6PaF+tFPn14SGAYKm+u9sj7Px9ov5vajSev9lpT4hU9UkItLNRLt3C1s3aPoWn1mN7jj6qyGG0tB544MH+x4eY4BNSrfHIrbWqjeLGfACGr4ogNaBaAv7GFfoALciE7Zooo9Hhxcr48PYCp+SQjsM8JhpM8Uh0tJOAhfJHSgdI8drK3qQ/UKbIdLiVkrorGcS3zXzoRWNj+wwVCfa4cWTFwTdCwaUMFZXRRAOA1kl09PWMf5855KY/8ilHJAw6IKS6BzoM=
  - secure: Phl1Vi8DMkZ28oWBcvs4jfii7tgiXQlbuThGfDa9nYuMllDd0vpG8686udZS5+63HV891PKZpq70+cK/JF4dyjgp/SLpTo5XBnHtBU/5/c1+Afeqtyu9sqb/ie7gDCWyWZqBL/QzL5rS72WRJCxYwK5Vt1KxVJkJf7Srpz0nNUBcw5D3UNfMkwRE2ey+3BBedFqpiCSrzuGo3bJsRg4jhM8Y/E1KuE4Z9k/X1bQ4ozKVHFBqOFrR45OpbglCGGneorr8JT7gqbwrdbShV285EdGBTF5+6uK69obAkR9I6a9MDi+4UUfZhvPjK4u2DwPiSMkKIvLocGUszDt6mjlg2J19ZNgeppSB2XXbOmuVnxcQznAjEbgCj8SK0X508mpwc7B0gjJ6+v7St786gWDclpTYix9IR3FAVOk5PsQUnUuoelLD/dw3cxazVd3wwE0rufx8ZEnrKXP9/7ETbmWKrcQJT7fS2WTE8CU9smmTWFdm1zkmvLTubTaE88hwPyX0F7QNQPAVTLNhQcMg8NauH62eS/fAcw74Fm+0swyKZ+t7zf/wWGIzypvaM4aOGmFjyYt1+3tNG9g9NcCknVBLCfIQB5sQnUpvxsonRi95ogKpykEZT61OcSeLWAldIPSwZ/HhgeN1nFIClPhjRNUxI1HMSb2JNrPgRLyuTNIsM6k=
  - secure: MZtbA9ykYbXm1H1Q7x0XgYiCrgWJ25wnQcZbhihgBEfja2MIjxRFm/Tf4Sue8LIs5L18oSoG4ZugIdelXTqyZpJbBz4NOaB4PZW1uxcc1vGnw5YAZ9U8Q9uJZTwiV+nyFmUMfucCx2t8P8jJh131BSj/6AelvzlgrfmnZmYkK7JZngZPsRmg1JvH8RcH3xOE8meKQRZSsM3gq4rSCF28ix+MxYAzgDmRXYkwY5cHe1Vyj0EdxdcT5e69dS79X0/Ds/3eUIcJoU3qx90PWpBnca7m+Yd37bC6O5zn53/9jEURQEn+E/T9MPEWmboL/kfQtVBPiXm/qQ6EDuzQpowsIzsp+7r25nIry4sZv8BcKRNBuBm42irVHPq6D5hxiSq/t9UOYZH0iQWv6JHWm4k07DBC47HT5tduxNjyxfC6Q8sBzIXx9L3fYaUbtw7yvERewUSMcMru+8Y+14cv0rREuIWMwLzcTlZzppxGGlnR39+iTwNiG8HfEC3ZJDjFLdBJwH8ecrARhFSmbSCBuLFRJhh5N3iuKavw2dzOwB4xKxlMpJOzUxSbm8KOb6moV/flFkcp9Zc6aKp/qOnO4u0WNYuHDlVx1vJFBv/m2yeJcnaS5V2VHuh27UUI2ibn/AToGonjvkFzjonBM02fhs9TC5pRKXt/3zxOWvReTQYOJgw=
